sudo: false

cache:
  pip: true

os:
  - linux
  - osx

dist: xenial

language: generic

env:
  - TASK=sdist PYTHON_VERSION="2.7"
  - TASK=sdist PYTHON_VERSION="3.5"
  - TASK=sdist PYTHON_VERSION="3.6"
  - TASK=sdist PYTHON_VERSION="3.7"

  - TASK=bdist PYTHON_VERSION="2.7"
  - TASK=bdist PYTHON_VERSION="3.5"
  - TASK=bdist PYTHON_VERSION="3.6"
  - TASK=bdist PYTHON_VERSION="3.7"

matrix:
  include:
    - os: osx
      env:
        COMPILER=gcc
        PYTHON_VERSION="3.7"

before_install:
  - export HOME_DIRECTORY="$HOME"
  - export BUILD_DIRECTORY="$TRAVIS_BUILD_DIR"
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        export OS_NAME="macos";
        if test -z "$COMPILER"; then
            export COMPILER="clang";
        fi
    else
        export OS_NAME="linux";
        export COMPILER="gcc";
    fi
  - export CONDA="$HOME/miniconda"
  - export PATH="$CONDA/bin:$PATH"
  - export CONDA_ENV="test-env"
  - export RANKEVAL_VER=$(head -n 1 rankeval/VERSION)

install:
  - source build_tools/travis/setup.sh

script:
  - bash build_tools/travis/test.sh

deploy:
  provider: pypi
  user: $PYPI_USER
  password: PYPI_PASS
  distributions: "sdist bdist_wheel"
  skip_existing: true
  skip_cleanup: true
  repo: hpclab/rankeval
  on:
    tags: true
    branch: master

notifications:
  slack:
    rooms: $SLACK_TOKEN
    on_success: change
    on_failure: always
    on_start: never
