sudo: false

cache:
  pip: true

os:
  - linux
  - osx

dist: xenial

language: generic

env:
  - TASK=sdist PYTHON_VERSION="2.7"
  - TASK=sdist PYTHON_VERSION="3.5"
  - TASK=sdist PYTHON_VERSION="3.6"
  - TASK=sdist PYTHON_VERSION="3.7"

  - TASK=bdist PYTHON_VERSION="2.7"
  - TASK=bdist PYTHON_VERSION="3.5"
  - TASK=bdist PYTHON_VERSION="3.6"
  - TASK=bdist PYTHON_VERSION="3.7"

before_install:
  - export BUILD_DIRECTORY="$TRAVIS_BUILD_DIR"
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        export OS_NAME="macos";
        if test -z "$COMPILER"; then
            export COMPILER="clang";
        fi
    else
        export OS_NAME="linux";
        export COMPILER="gcc";
    fi

install:
  - source build_tools/travis/setup.sh

script:
  - bash build_tools/travis/test.sh

jobs:
  include:
    - stage: test
      os: osx
      env:
        COMPILER=gcc
        PYTHON_VERSION="3.7"

    - stage: deploy
      if: tag IS present
      os: osx
      env:
        TASK=bdist
        PYTHON_VERSION="2.7"
      script:
        - build_tools/travis/deploy.sh

    - stage: deploy
      if: tag IS present
      os: osx
      env:
        TASK=bdist
        PYTHON_VERSION="3.5"
      script:
        - build_tools/travis/deploy.sh

    - stage: deploy
      if: tag IS present
      os: osx
      env:
        TASK=bdist
        PYTHON_VERSION="3.6"
      script:
        - build_tools/travis/deploy.sh

    - stage: deploy
      if: tag IS present
      os: osx
      env:
        TASK=bdist
        PYTHON_VERSION="3.7"
      script:
        - build_tools/travis/deploy.sh

    - stage: deploy
      if: tag IS present
      sudo: required
      services:
        - docker
      env:
        DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
        PLAT=manylinux1_x86_64
      before_install: skip
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -e PLAT=$PLAT -e PYPI_USER=$PYPI_USER -e PYPI_PASS=$PYPI_PASS -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build_tools/build_wheels.sh
        - ls wheelhouse/

    - stage: deploy
      if: tag IS present
      sudo: required
      services:
        - docker
      env:
        DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
        PLAT=manylinux2010_x86_64
      before_install: skip
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -e PLAT=$PLAT -e PYPI_USER=$PYPI_USER -e PYPI_PASS=$PYPI_PASS -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build_tools/build_wheels.sh
        - ls wheelhouse/

notifications:
  slack:
    rooms: $SLACK_TOKEN
    on_success: change
    on_failure: always